### ISSUE TITLE
Error converting empty table?

### ISSUE THREAD

**Issue by philmitchell** [techouse/mysql-to-sqlite3#2]
Conversion fails when the script hits an empty table:

```
└─ $ ▶ ./mysql2sqlite.py -f output.sqlite -u root -p '' -d ITIS
2019-04-16 07:43:23 INFO     Transferring table change_comments
0it [00:00, ?it/s]
2019-04-16 07:43:23 ERROR    _create_table failed creating table change_operations: Unread result found
```
By dropping all the empty tables, I was able to get the script to run to completion. It seems to bail out *after* creating the empty table, because the dropped tables do show up in my sqlite version.

Thanks for creating this ... huge help!

**Comment by techouse** [comment]
Well, you know how it is :D One can't predict everything. Can you maybe send me the database with some dummy data so I can try and fix my script to work with this?

**Comment by philmitchell** [comment]
I took a look, but not being a python guy did not spend much time--sorry! The db I'm working with is a public dataset from [ITIS](https://www.itis.gov/downloads/index.html). Here is a link to the [MySQL bulk download](https://www.itis.gov/downloads/itisMySQLBulk.zip) (~45M zipfile)

**Comment by techouse** [comment]
Thanx! Will look into it as soon as I got some time on my hands :)

**Comment by techouse** [comment]
Fixed it. There were 2 issues regarding this database actually. I'm quite happy you pointed them out to me since they are quite unusual to be found in the real World:

1. The 1st one was related to the table being empty and the MySQL cursor still having unread results, although I kinda don't quite understand how that can be. That was [fixed with a simple `if` condition](https://github.com/techouse/mysql-to-sqlite3/commit/75cc18927d542f40458463bfca29e48e9218b0b6#diff-25c9dbb7f520041882dbe900fe524a7eR214).

2. The 2nd one was related to transferring a table without any primary key. That was also [a trivial fix](https://github.com/techouse/mysql-to-sqlite3/commit/6fa44798cf3e10825427c97302b6a56e954e0cdb).

Thanks again for pointing this out! Much obliged 😇

**Comment by philmitchell** [comment]
Thanks again for publishing this, Klemen, it helped me a lot. Cheers ...
